name: Build & Check CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly-2024-05-02]
        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
        targets: ${{ matrix.targets }}
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --target ${{ matrix.targets }} --all-features -- -A clippy::new_without_default
    - name: Build
      run: cargo build --target ${{ matrix.targets }} --all-features
    - name: Unit test
      if: ${{ matrix.targets == 'x86_64-unknown-linux-gnu' }}
      run: cargo test --target ${{ matrix.targets }} -- --nocapture
